resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: nagarjuntestpipelinegit                       # <-- replace with your integration
      path: amithkm/rna_test    # <-- replace with your repository name
      branches:
        include: master


  - name: dbp_image_3
    type: Image
    configuration:
      registry: nagarjunarttoken                                # <-- replace with your artifactory integration
      sourceRepository: docker               # <-- required if registry is Artifactory
      imageName: amithmutak.jfrog.io/docker/rnaiot-msgprocess/iotmsgprocess   # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: nagarjunarttoken # <-- replace with your artifactory integration
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: nagarjunarttoken # <-- replace with your artifactory integration
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: rnaiot_pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: amithmutak.jfrog.io/docker/rnaiot-msgprocess/iotmsgprocess   # replace with your image path and name
          #dockerImageTag: ${run_number}
          dockerImageTag: latest
          inputResources:
            - name: dbp_repo
              #  To trigger pipeline automatically - By defualt this is ON, so need not define explicitly
              trigger: true
          integrations:
            - name: nagarjunarttoken                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker
          integrations:
            - name: nagarjunarttoken                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image_3

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: docker
          integrations:
            - name: nagarjunarttoken # <-- replace with your artifactory integration
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
            
