resources:
  - name: dbp_repo_1
    type: GitRepo
    configuration:
      gitProvider: jfrogsupport_test_git                       # <-- replace with your integration
      path: amithkm/rna_test    # <-- replace with your repository name
      branches:
        include: master


  - name: dbp_image_4
    type: Image
    configuration:
      registry: jfrogsupport_testart                                # <-- replace with your artifactory integration
      sourceRepository: rnaiot-msgprocess               # <-- required if registry is Artifactory
      imageName: nagarjun.jfrog.io/rnaiot-msgprocess/iotmsgprocess   # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info_1
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrogsupport_testart # <-- replace with your artifactory integration
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info_1
    type: BuildInfo
    configuration:
      sourceArtifactory: jfrogsupport_testart # <-- replace with your artifactory integration
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: rnaiot_pipeline_dbp
    steps:
      - name: docker_build_1
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: nagarjun.jfrog.io/rnaiot-msgprocess/iotmsgprocess   # replace with your image path and name
          #dockerImageTag: ${run_number}
          dockerImageTag: latest
          inputResources:
            - name: dbp_repo_1
              #  To trigger pipeline automatically - By defualt this is ON, so need not define explicitly
              trigger: true
          integrations:
            - name: jfrogsupport_testart                            # <-- replace with your artifactory integration

      - name: docker_push_1
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: rnaiot-msgprocess
          integrations:
            - name: jfrogsupport_testart                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build_1
          outputResources:
            - name: dbp_image_4

      - name: publish_dbp_build_1
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_1
          outputResources:
            - name: dbp_build_info_1

      - name: promote_dbp_build_1
        type: PromoteBuild
        configuration:
          targetRepository: rnaiot-msgprocess
          integrations:
            - name: jfrogsupport_testart # <-- replace with your artifactory integration
          inputResources:
            - name: dbp_build_info_1
          outputResources:
            - name: dbp_promoted_build_info_1
            

